### PR TITLE
Http headers option for ApiClient

### PR DESCRIPTION
**Pull request by fpassaniti**
## Summary

The goal for this PR is to provide http headers when creating the ApiClient

### Changes

It adds a new param in ApiClient config and parameters

### Changelog

In the ApiClient: It's now possible to provide a `headers` parameter, to provide specific HTTP headers. 
NB: If both an Authorization header and an apiKey are provided, the Authorization header from the headers param will be overridden by the apiKey. 

## Review checklist

- [ ] Description is complete
- [ ] Commits respect the [Conventional Commits Specification](https://github.com/opendatasoft/ods-dataviz-sdk/blob/main/CONTRIBUTING.md#commit-messages)
- [ ] 2 reviewers (1 if trivial)
- [ ] Tests coverage has improved
- [ ] Code is ready for a release on NPM

### CODE REVIEW

**Comment by fpassaniti** [comment]
Usage in a reactjs app for example, to get the sessionid cookie from the session, and use it for backend queries to the API :

_page.tsx :_
```

async function getData() {
    const sessionid = cookies().get("sessionid")
    let headers = {}
    if (sessionid) {
        headers = {
            Cookie: `sessionid=${sessionid.value};`
        }
    }

    const client = new ApiClient({domain: 'preprod-banquedefrance', headers});

    try {
        return await client.get('catalog/datasets?limit=0&offset=0&timezone=UTC&include_links=false&include_app_metas=false')
    } catch (e) {
        console.log(e)
        return {total_count: -1}
    }
}
```

**Review by wmai — APPROVED** [review]
Nicely done, looks perfectly good to me 💪 Since Benoit won't be back anytime soon, would you need someone else to review this PR so that we can release this feature quickly? If so, maybe @KevinFabre-ods could be your second reviewer?

**Comment by KevinFabre-ods** [comment]
Yes, I'll do the review

**Review by KevinFabre-ods — APPROVED** [review]
LGTM 🟢 

For next development, please follow our [convention about naming commits](https://github.com/opendatasoft/ods-dataviz-sdk/blob/main/CONTRIBUTING.md#commit-messages). It helps a lot when publishing new packages versions. 

Please don't merge yet this PR. I'll squash some of PR's commits to make a minor incrementation for the api-client package.

**Comment by KevinFabre-ods** [comment]
@fpassaniti New version is now available
https://www.npmjs.com/package/@opendatasoft/api-client/v/21.2.0

**Pull request merged**
